//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangjing.SQLServerDAL.wcfnotice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcfnotice.IUserNoticeService")]
    public interface IUserNoticeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserNoticeService/AddMessage", ReplyAction="http://tempuri.org/IUserNoticeService/AddMessageResponse")]
        void AddMessage(int userid, int usertype, int messagetype, string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserNoticeServiceChannel : Hangjing.SQLServerDAL.wcfnotice.IUserNoticeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserNoticeServiceClient : System.ServiceModel.ClientBase<Hangjing.SQLServerDAL.wcfnotice.IUserNoticeService>, Hangjing.SQLServerDAL.wcfnotice.IUserNoticeService {
        
        public UserNoticeServiceClient() {
        }
        
        public UserNoticeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserNoticeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserNoticeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserNoticeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddMessage(int userid, int usertype, int messagetype, string message) {
            base.Channel.AddMessage(userid, usertype, messagetype, message);
        }
    }
}
